/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CtaSection = {
  _type: "ctaSection";
  title?: string;
  body?: string;
  links?: Array<
    {
      _key: string;
    } & CtaLink
  >;
};

export type FaqSection = {
  _type: "faqSection";
  title?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "faq";
    _key: string;
  }>;
};

export type PricingSection = {
  _type: "pricingSection";
  title?: string;
  plans?: Array<{
    name?: string;
    price?: string;
    description?: string;
    features?: Array<string>;
    highlighted?: boolean;
    _type: "plan";
    _key: string;
  }>;
};

export type TestimonialsSection = {
  _type: "testimonialsSection";
  title?: string;
  quotes?: Array<{
    quote?: string;
    name?: string;
    role?: string;
    _type: "quote";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SplitVisualSection = {
  _type: "splitVisualSection";
  eyebrow?: string;
  title?: string;
  body?: string;
  bullets?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  reverse?: boolean;
};

export type FeatureGridSection = {
  _type: "featureGridSection";
  eyebrow?: string;
  title?: string;
  body?: string;
  features?: Array<{
    title?: string;
    body?: string;
    stat?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type LogoStripSection = {
  _type: "logoStripSection";
  title?: string;
  logos?: Array<string>;
};

export type HeroSection = {
  _type: "heroSection";
  eyebrow?: string;
  title?: string;
  body?: string;
  metricLabel?: string;
  metricValue?: string;
  links?: Array<
    {
      _key: string;
    } & CtaLink
  >;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
  variant?: "primary" | "secondary" | "ghost";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & FeatureGridSection)
    | ({
        _key: string;
      } & SplitVisualSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & PricingSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CtaSection
  | FaqSection
  | PricingSection
  | TestimonialsSection
  | SanityImageAssetReference
  | SplitVisualSection
  | FeatureGridSection
  | LogoStripSection
  | HeroSection
  | CtaLink
  | Seo
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    "slug": slug.current,    "updatedAt": _updatedAt,    seo {      title,      description,      canonical,      image {        alt,        "url": asset->url      }    },    sections[] {      ...,      image {        alt,        "url": asset->url      },      links[] {        label,        href,        variant      },      features[] {        title,        body,        stat      },      quotes[] {        quote,        name,        role      },      plans[] {        name,        price,        description,        highlighted,        features[]      },      faqs[] {        question,        answer      },      logos[]    }  }
export type PAGE_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  updatedAt: string;
  seo: {
    title: string | null;
    description: string | null;
    canonical: string | null;
    image: {
      alt: string | null;
      url: string | null;
    } | null;
  } | null;
  sections: Array<
    | {
        _key: string;
        _type: "ctaSection";
        title?: string;
        body?: string;
        links: Array<{
          label: string | null;
          href: string | null;
          variant: "ghost" | "primary" | "secondary" | null;
        }> | null;
        image: null;
        features: null;
        quotes: null;
        plans: null;
        faqs: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "faqSection";
        title?: string;
        faqs: Array<{
          question: string | null;
          answer: string | null;
        }> | null;
        image: null;
        links: null;
        features: null;
        quotes: null;
        plans: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "featureGridSection";
        eyebrow?: string;
        title?: string;
        body?: string;
        features: Array<{
          title: string | null;
          body: string | null;
          stat: string | null;
        }> | null;
        image: null;
        links: null;
        quotes: null;
        plans: null;
        faqs: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        eyebrow?: string;
        title?: string;
        body?: string;
        metricLabel?: string;
        metricValue?: string;
        links: Array<{
          label: string | null;
          href: string | null;
          variant: "ghost" | "primary" | "secondary" | null;
        }> | null;
        image: null;
        features: null;
        quotes: null;
        plans: null;
        faqs: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "logoStripSection";
        title?: string;
        logos: Array<string> | null;
        image: null;
        links: null;
        features: null;
        quotes: null;
        plans: null;
        faqs: null;
      }
    | {
        _key: string;
        _type: "pricingSection";
        title?: string;
        plans: Array<{
          name: string | null;
          price: string | null;
          description: string | null;
          highlighted: boolean | null;
          features: Array<string> | null;
        }> | null;
        image: null;
        links: null;
        features: null;
        quotes: null;
        faqs: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "splitVisualSection";
        eyebrow?: string;
        title?: string;
        body?: string;
        bullets?: Array<string>;
        image: {
          alt: string | null;
          url: string | null;
        } | null;
        reverse?: boolean;
        links: null;
        features: null;
        quotes: null;
        plans: null;
        faqs: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "testimonialsSection";
        title?: string;
        quotes: Array<{
          quote: string | null;
          name: string | null;
          role: string | null;
        }> | null;
        image: null;
        links: null;
        features: null;
        plans: null;
        faqs: null;
        logos: null;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PAGES_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current  }
export type PAGES_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    "updatedAt": _updatedAt,\n    seo {\n      title,\n      description,\n      canonical,\n      image {\n        alt,\n        "url": asset->url\n      }\n    },\n    sections[] {\n      ...,\n      image {\n        alt,\n        "url": asset->url\n      },\n      links[] {\n        label,\n        href,\n        variant\n      },\n      features[] {\n        title,\n        body,\n        stat\n      },\n      quotes[] {\n        quote,\n        name,\n        role\n      },\n      plans[] {\n        name,\n        price,\n        description,\n        highlighted,\n        features[]\n      },\n      faqs[] {\n        question,\n        answer\n      },\n      logos[]\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': PAGES_SLUGS_QUERY_RESULT;
  }
}
